CREATE TABLE IF NOT EXISTS orders (
                                      order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      instrument_id INTEGER NOT NULL,
                                      order_date DATE NOT NULL,
                                      order_type VARCHAR(10) NOT NULL, -- e.g., 'BUY', 'SELL'
    quantity NUMERIC(18, 8) NOT NULL,
    price NUMERIC(18, 8) NOT NULL,
    status VARCHAR(50) NOT NULL -- e.g., 'PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED'
    );

CREATE TABLE IF NOT EXISTS trades (
                                      trade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      order_id INTEGER NOT NULL,
                                      trade_date TIMESTAMP WITH TIME ZONE NOT NULL,
                                      quantity NUMERIC(18, 8) NOT NULL,
    price NUMERIC(18, 8) NOT NULL
    );

CREATE TABLE IF NOT EXISTS feed_count (
                                          feed_count_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          feed_date DATE NOT NULL,
                                          feed_name VARCHAR(255) NOT NULL,
    feed_count BIGINT DEFAULT 0
    );

--drop table orders;
--drop table trades;
--drop table feed_count;
--truncate table orders;
--truncate table trades;
--truncate table feed_count;
--truncate table databasechangelog;
--truncate table databasechangeloglock;

